apiVersion: v2
name: prometheus-windows-exporter
description: A Helm chart for prometheus windows-exporter
keywords:
  - windows-exporter
  - windows
  - prometheus
  - exporter
type: application
version: 0.3.1
appVersion: 0.25.1
home: https://github.com/prometheus-community/windows_exporter/
sources:
  - https://github.com/prometheus-community/windows_exporter/
maintainers:
  - name: jkroepke
    email: github@jkroepke.de
