apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-sql-exporter.fullname" . }}
  labels:
    {{- include "prometheus-sql-exporter.labels" $ | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yml: |
    {{- .Values.config | toYaml | nindent 4 }}
