apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-kafka-exporter.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "prometheus-kafka-exporter.name" . }}
    chart: {{ template "prometheus-kafka-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if and (eq .Values.service.type "LoadBalancer") (.Values.service.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: exporter-port
      protocol: TCP
      name: exporter-port
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "prometheus-kafka-exporter.name" . }}
    release: {{ .Release.Name }}
