apiVersion: v2
appVersion: "v1.2.1"
description: Prometheus Pingmesh Exporter
home: https://stack.kubeservice.cn/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
  - prometheus
  - pingmesh
  - monitoring
maintainers:
  - email: dongjiang1989@126.com
    name: dongjiang1989
name: prometheus-pingmesh-exporter
sources:
  - https://github.com/kubeservice-stack/pingmesh-agent
type: application
version: 0.4.0
