apiVersion: v2
name: prom-label-proxy
description: A proxy that enforces a given label in a given PromQL query.
type: application
version: 0.8.0
appVersion: "v0.10.0"
home: "https://github.com/prometheus-community/prom-label-proxy"
keywords:
  - metric
  - monitoring
  - prometheus
maintainers:
  - name: jkroepke
    email: github@jkroepke.de
