{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-operator-admission-webhook.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
