{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
  labels:
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
rules:
  {{- if and .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ include "prometheus-operator-admission-webhook.fullname" . }}
    verbs:
    - use
{{- end }}
{{- end }}
