{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
  labels:
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-operator-admission-webhook.serviceAccountName" . }}
{{- end }}
