{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
  {{- end }}
spec:
  endpoints:
    - port: https
      path: /metrics
      scheme: https
      interval: {{ default "30s" .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ default "10s" .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ default false .Values.serviceMonitor.honorLabels }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  {{- else }}
  jobLabel: {{ include "prometheus-operator-admission-webhook.fullname" . }}
  {{- end }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceMonitor.attachMetadata }}
  attachMetadata:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-operator-admission-webhook.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "prometheus-operator-admission-webhook.namespace" . }}
{{- end }}
