---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ default 443 .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "prometheus-operator-admission-webhook.selectorLabels" . | nindent 4 }}
