version: 0.2

env:
  # ==================== #
  #  Ref: SECRET CONFIG  #
  # ==================== #
  parameter-store:
    BUILDNUMBER: /devopscorner/cicd/staging/repo/golang-bedrock/buildnumber
    STORE_AWS_ACCOUNT: /devopscorner/cicd/staging/credentials/aws_account
    STORE_AWS_ACCESS_KEY: /devopscorner/cicd/staging/credentials/aws_access_key
    STORE_AWS_SECRET_KEY: /devopscorner/cicd/staging/credentials/aws_secret_key
    STORE_AWS_PROFILE: /devopscorner/cicd/staging/credentials/aws_profile
    STORE_REPO_URL: /devopscorner/cicd/staging/repo/golang-bedrock/url
    STORE_REPO_BRANCH: /devopscorner/cicd/staging/repo/golang-bedrock/branch
    STORE_REPO_FOLDER: /devopscorner/cicd/staging/repo/golang-bedrock/folder
    STORE_EKS_CLUSTER: /devopscorner/cicd/staging/eks_cluster
    STORE_DOCKERHUB_USERNAME: /devopscorner/cicd/staging/repo_credentials/dockerhub/username
    STORE_DOCKERHUB_PASSWORD: /devopscorner/cicd/staging/repo_credentials/dockerhub/password_encoded

  # ===================================== #
  #  Ref: Pipeline Environment Variables  #
  # ===================================== #
  variables:
    ENV_CICD: "nonprod"
    AWS_DEFAULT_REGION: "us-west-2"
    INFRA_CICD: "terraform/devopscorner/devopspoc/eks"
    INFRA_CICD_PATH: "golang-bedrock"
    INFRA_ECR_PATH: "devopscorner/golang-bedrock"

phases:
  build:
    commands:
      # ============== #
      #  Docker Login  #
      # ============== #
      - DOCKERHUB_PASSWORD=`echo -n ${STORE_DOCKERHUB_PASSWORD} | base64 -d`
      - echo $DOCKERHUB_PASSWORD | docker login --username ${STORE_DOCKERHUB_USERNAME} --password-stdin
      # ========================= #
      #  Refactoring AWS Account  #
      # ========================= #
      - cd ${CODEBUILD_SRC_DIR} && find ./ -type f -exec sed -i "s/YOUR_AWS_ACCOUNT/${STORE_AWS_ACCOUNT}/g" {} \;
      # ============= #
      #  Build Image  #
      # ============= #
      - make ecr-build-alpine ARGS=${STORE_AWS_ACCOUNT} CI_PATH=${INFRA_ECR_PATH}
      # ============== #
      #  Unit Testing  #
      # ============== #
      # - make unit-test
      # ============ #
      #  Tags Image  #
      # ============ #
      - make ecr-tag-alpine ARGS=${STORE_AWS_ACCOUNT} CI_PATH=${INFRA_ECR_PATH}
      - docker images --format "{{.Repository}}:{{.Tag}}" | grep ${INFRA_ECR_PATH}
      # ============ #
      #  Push Image  #
      # ============ #
      - make ecr-push-alpine ARGS=${STORE_AWS_ACCOUNT} CI_PATH=${INFRA_ECR_PATH}

artifacts:
  files:
    - .aws/*
    - src/*
    - dockerhub-build.sh
    - dockerhub-push.sh
    - dockerhub-tag.sh
    - ecr-build.sh
    - ecr-push.sh
    - ecr-tag.sh
    - Makefile
  name: "artifact-$(date '+%Y%m%d-%H%M%S')"