{{- if and .Values.networkPolicy.enabled .Values.jobs.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-5"
    {{- with .Values.jobs.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.jobs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
  egress:
  - {}
  policyTypes:
  - Egress
{{- end }}
