{{- if and .Values.jobs.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
  namespace: {{ template "prometheus-operator-admission-webhook.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.jobs.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.jobs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
    namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
{{- end }}
