{{- if .Values.jobs.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
  namespace: {{ include "prometheus-operator-admission-webhook.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.jobs.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ include "prometheus-operator-admission-webhook.fullname" . }}-aux
    {{- include "prometheus-operator-admission-webhook.labels" . | nindent 4 }}
    {{- with .Values.jobs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.jobs.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | trim | nindent 2 }}
{{- end }}
{{- end }}