{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "prometheus-pgbouncer-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-pgbouncer-exporter.name" . }}
    chart: {{ template "prometheus-pgbouncer-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "prometheus-pgbouncer-exporter.name" . }}
      release: {{ .Release.Name }}
{{- end }}
