{{- if not (or .Values.config.datasource.passwordSecret .Values.config.datasourceSecret .Values.config.datasource.passwordFile ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-pgbouncer-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-pgbouncer-exporter.name" . }}
    chart: {{ template "prometheus-pgbouncer-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  data_source_password: {{ .Values.config.datasource.password | default "somepaswword" | b64enc }}
{{- end -}}
