apiVersion: v1
description: Stackdriver exporter for Prometheus
name: prometheus-stackdriver-exporter
version: 4.5.0
appVersion: v0.15.0
home: https://www.stackdriver.com/
sources:
  - https://github.com/prometheus-community/stackdriver_exporter
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-stackdriver-exporter
keywords:
  - metrics
  - stackdriver
  - monitoring
maintainers:
  - name: apenney
    email: apenney@gmail.com
  - name: rpahli
    email: pahli88@googlemail.com
