apiVersion: v1
description: Elasticsearch stats exporter for Prometheus
name: prometheus-elasticsearch-exporter
version: 5.8.1
kubeVersion: ">=1.10.0-0"
appVersion: "v1.7.0"
home: https://github.com/prometheus-community/elasticsearch_exporter
sources:
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
keywords:
  - metrics
  - elasticsearch
  - monitoring
maintainers:
  - name: svenmueller
    email: sven.mueller@commercetools.com
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: zeritti
    email: rootsandtrees@posteo.de
