apiVersion: v2
appVersion: "v0.11.0"
description: Druid exporter to monitor druid metrics with Prometheus
name: prometheus-druid-exporter
version: 1.1.0
kubeVersion: ">=1.16.0-0"
type: application
home: https://github.com/opstree/druid-exporter
maintainers:
  - email: abhishekbhardwaj510@gmail.com
    name: iamabhishek-dubey
  - email: sandeep@opstree.com
    name: sandy724
sources:
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-druid-exporter
  - https://github.com/opstree/druid-exporter
keywords:
  - kubernetes
  - apache
  - druid
  - exporter
  - prometheus
  - grafana
icon: https://github.com/opstree/druid-exporter/blob/master/static/druid-exporter-logo.svg
annotations:
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-druid-exporter
