{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jiralert.fullname" . }}
  namespace: {{ template "jiralert.namespace" . }}
  labels:
    {{- include "jiralert.labels" . | nindent 4 }}
data:
  {{- if .Values.tplConfig }}
  {{- if .Values.configString }}
  jiralert.yml: {{ tpl (.Values.configString) . | b64enc }}
  {{- else }}
  jiralert.yml: {{ tpl (.Values.config | toYaml) . | b64enc }}
  {{- end }}
  {{- else }}
  jiralert.yml: {{ toYaml .Values.config | b64enc }}
  {{- end}}
  jiralert.tmpl: {{ tpl .Values.issueTemplate . | b64enc }}
{{- end }}
