receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      global:
        scrape_interval: 10s
      scrape_configs:
        - job_name: 'otc-metrics'
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:

exporters:
  awsprometheusremotewrite:
    endpoint: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-xxx/api/v1/remote_write
    aws_endpoint: https://aps-workspaces.us-west-2.amazonaws.com
    aws_region: us-west-2
    namespace: "otel"
    max_batch_size: 1024
    max_connections: 2

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsprometheusremotewrite]
    metrics:
      receivers: [prometheus]
      exporters: [awsprometheusremotewrite]
