{
 "title": "[NONPROD] XIGNALS / LOG / XIGNALS-OTEL",
 "description": "Xignals Logs (xignals-logs-*) Filter",
 "tags": [
  "opensearch",
  "log",
  "xignals",
  "kubernetes",
  "prometheus",
  "alva"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Query" },
   { "name": "datasource", "query": "grafana-opensearch-datasource" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Ingestions @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "FILTERS",
     "bucketAggs": [
      { "field": "${Filters}", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "${Query}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status INFO @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time for the \"INFO\" status.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status ERROR @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time for the \"ERROR\" status.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "${Filters}", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status DEBUG @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time for the \"DEBUG\" status.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!(info) OR !(error) OR !(warning) OR !(critical) OR !(trace)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status WARNING @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time for the \"WARNING\" status.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "WARNING",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warning",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status CRITICAL @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time for the \"CRITICAL\" status.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "CRITICAL",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "critical",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status TRACE @ Time",
   "type": "stat",
   "description": "This panel displays the total number of ingestions over time for the \"TRACE\" status.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "TRACE",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "trace",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Stream Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ingestion Logs - Graph",
   "type": "timeseries",
   "description": "This panel titled \"Panel Title\" displays a table format of counts over time. It uses the \"Xignals Logs\" datasource and is part of the \"Xignals EMI\" dashboard.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "FILTERS",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "${Query}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ingestion Logs - Hits",
   "type": "table",
   "description": "This panel displays the count of INFO, ERROR, and DEBUG log messages over time for non-production environments.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "info",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "error",
     "timeField": "@timestamp"
    },
    {
     "alias": "DEBUG",
     "bucketAggs": [
      { "field": "${Filters}", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!(info) OR !(error) OR !(warning) OR !(critical) OR !(trace)",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARNING",
     "bucketAggs": [
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "warning",
     "timeField": "@timestamp"
    },
    {
     "alias": "CRITICAL",
     "bucketAggs": [
      { "field": "${Filters}", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "critical",
     "timeField": "@timestamp"
    },
    {
     "alias": "TRACE",
     "bucketAggs": [
      { "field": "${Filters}", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "trace",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Stream Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Logs Index",
   "type": "table",
   "description": "Displays a detailed log index segmented by information, error, and debug levels with time-based histograms.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "${Filters}", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "${Query}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs Detail",
   "type": "table",
   "description": "Displays detailed logs with timestamps to monitor and assess system activities within the non-production environment.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "${Filters}", "id": "1", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "${Query}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}