{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-pingdom-exporter.secretName" . }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus-pingdom-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.pingdom.user | b64enc }}
  password: {{ .Values.pingdom.password | b64enc }}
  appId: {{ .Values.pingdom.appId | b64enc }}
  accountEmail: {{ .Values.pingdom.accountEmail | b64enc }}
{{- end }}