postgresql:
  enabled: true
  fullnameOverride: ci-postgres
  global:
    postgresql:
      auth:
        postgresPassword: "password"
rbac:
  create: true
  pspEnabled: false
extraContainers:
  - name: pgbouncer
    image: bitnami/pgbouncer:latest
    env:
      - name: POSTGRESQL_PASSWORD
        value: "password"
      - name: PGBOUNCER_EXTRA_FLAGS
        value: "--verbose"
      - name: "POSTGRESQL_HOST"
        value: ci-postgres
      - name: PGBOUNCER_AUTH_USER
        value: "postgres"
      - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
        value: "extra_float_digits"
    volumeMounts:
      - name: pgbouncer-config
        mountPath: /opt/bitnami/pgbouncer/conf
      - name: pgbouncer-logs
        mountPath: /opt/bitnami/pgbouncer/logs
      - name: pgbouncer-tmp
        mountPath: /opt/bitnami/pgbouncer/tmp
extraVolumes:
  - name: pgbouncer-config
    emptyDir: {}
  - name: pgbouncer-logs
    emptyDir: {}
  - name: pgbouncer-tmp
    emptyDir: {}
config:
  datasource:
    host: localhost
    port: 6432
    password: "password"
