{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "grafana-tempo.metrics-generator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: metrics-generator
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.metricsGenerator.replicaCount }}
  {{- if .Values.metricsGenerator.updateStrategy }}
  strategy: {{- toYaml .Values.metricsGenerator.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.metricsGenerator.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: metrics-generator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/tempo-configmap.yaml") . | sha256sum }}
        {{- if .Values.metricsGenerator.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: metrics-generator
        tempo-gossip-member: "true"
    spec:
      serviceAccountName: {{ template "grafana-tempo.serviceAccountName" . }}
      {{- include "grafana-tempo.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.metricsGenerator.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metricsGenerator.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.metricsGenerator.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.metricsGenerator.podAffinityPreset "component" "metrics-generator" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.metricsGenerator.podAntiAffinityPreset "component" "metrics-generator" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.metricsGenerator.nodeAffinityPreset.type "key" .Values.metricsGenerator.nodeAffinityPreset.key "values" .Values.metricsGenerator.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.metricsGenerator.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.metricsGenerator.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metricsGenerator.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.metricsGenerator.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.metricsGenerator.priorityClassName }}
      priorityClassName: {{ .Values.metricsGenerator.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.metricsGenerator.schedulerName }}
      schedulerName: {{ .Values.metricsGenerator.schedulerName }}
      {{- end }}
      {{- if .Values.metricsGenerator.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.metricsGenerator.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.metricsGenerator.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: grafana-tempo-metrics-generator
          image: {{ template "grafana-tempo.image" . }}
          imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
          {{- if .Values.metricsGenerator.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.metricsGenerator.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.metricsGenerator.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.metricsGenerator.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - -target=metrics-generator
            - -config.file=/bitnami/grafana-tempo/conf/tempo.yaml
            - -mem-ballast-size-mbs={{ .Values.tempo.memBallastSizeMbs }}
          {{- end }}
          {{- if .Values.metricsGenerator.extraEnvVars }}
          env: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.metricsGenerator.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.metricsGenerator.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.tempo.containerPorts.web }}
              name: http
            - containerPort: {{ .Values.tempo.containerPorts.gossipRing }}
              name: http-memberlist
            - containerPort: {{ .Values.tempo.containerPorts.grpc }}
              name: grpc
          {{- if .Values.metricsGenerator.resources }}
          resources: {{- toYaml .Values.metricsGenerator.resources | nindent 12 }}
          {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.metricsGenerator.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.metricsGenerator.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.metricsGenerator.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /ready
              port: {{ .Values.tempo.containerPorts.web }}
          {{- end }}
          {{- if .Values.metricsGenerator.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.metricsGenerator.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.metricsGenerator.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /ready
              port: {{ .Values.tempo.containerPorts.web }}
          {{- end }}
          {{- if .Values.metricsGenerator.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.metricsGenerator.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.metricsGenerator.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- end }}
          {{- if .Values.metricsGenerator.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tempo-config
              mountPath: /bitnami/grafana-tempo/conf/tempo.yaml
              subPath: tempo.yaml
            - name: overrides-config
              mountPath: /bitnami/grafana-tempo/conf/overrides.yaml
              subPath: overrides.yaml
            - name: data
              mountPath: {{ .Values.tempo.dataDir }}
          {{- if .Values.metricsGenerator.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.metricsGenerator.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.metricsGenerator.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: tempo-config
          configMap:
            name: {{ template "grafana-tempo.tempoConfigmapName" . }}
        - name: overrides-config
          configMap:
            name: {{ template "grafana-tempo.overridesConfigmapName" . }}
        {{- if .Values.metricsGenerator.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.metricsGenerator.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
