apiVersion: v2
name: prometheus-systemd-exporter
description: A Helm chart for prometheus systemd-exporter
type: application
version: 0.2.2
appVersion: "0.6.0"
home: https://github.com/prometheus-community/systemd_exporter
sources:
- https://github.com/prometheus-community/systemd_exporter
maintainers:
- name: capuche2412
  email: aleroux@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
