apiVersion: v2
name: jiralert
description: A Helm chart for Kubernetes to install jiralert
type: application
version: 1.7.1
appVersion: "v1.3.0"
home: "https://github.com/prometheus-community/jiralert"
keywords:
  - monitoring
  - prometheus
  - alerting
  - jiralert
maintainers:
  - name: jkroepke
    email: github@jkroepke.de
  - name: zanhsieh
    email: zanhsieh@gmail.com
