{{- if not .Values.configMapFile -}}
{{- $fullName := include "prometheus-modbus-exporter.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prometheus-modbus-exporter.labels" . | nindent 4 }}
data:
  modbus.yml: |
    modules:
{{- toYaml .Values.modules | nindent 4 }}
{{- end }}
