# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: grafana-tempo-query
      image: docker.io/bitnami/grafana-tempo-query:2.3.0-debian-11-r3
    - name: grafana-tempo-vulture
      image: docker.io/bitnami/grafana-tempo-vulture:2.3.0-debian-11-r1
    - name: grafana-tempo
      image: docker.io/bitnami/grafana-tempo:2.3.0-debian-11-r2
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
apiVersion: v2
appVersion: 2.3.0
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 6.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Grafana Tempo is a distributed tracing system that has out-of-the-box integration with Grafana. It is highly scalable and works with many popular tracing protocols.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/grafana-tempo/img/grafana-tempo-stack-220x234.png
keywords:
- grafana
- tracing
- metrics
- infrastructure
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: grafana-tempo
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/grafana-tempo
version: 2.5.5
