#
# values.yaml
#

# Security
## Add .pgpass file to root of pgAdmin storage
# For details Sse `Advanced tab -> Password File` in
# https://www.pgadmin.org/docs/pgadmin4/4.23/server_dialog.html

env:
  pgpassfile: /var/lib/pgadmin/storage/pgadmin/file.pgpass
extraSecretMounts:
- name: pgpassfile
  secret: pgpassfile
  subPath: pgpassfile
  mountPath: "/var/lib/pgadmin/storage/pgadmin/file.pgpass"
  readOnly: true
VolumePermissions:
  # chown -R pgadmin:pgadmin /var/lib/pgadmin
  enabled: true
extraInitContainers: |
  - name: add-folder-for-pgpass
    image: "dpage/pgadmin4:4.23"
    command: ["/bin/mkdir", "-p", "/var/lib/pgadmin/storage/pgadmin"]
    volumeMounts:
      - name: pgadmin-data
        mountPath: /var/lib/pgadmin
    securityContext:
      runAsUser: 5050

#
# secrets.yaml
#
---
apiVersion: v1
kind: Secret
metadata:
  name: pgpassfile
type: Opaque
stringData:
  # https://www.postgresql.org/docs/9.4/libpq-pgpass.html
  pgpassfile: |
    hostname:port:database:username:password
