apiVersion: v1
kind: Secret
metadata:
  name: golang-bedrock
  namespace: monitoring
type: Opaque
data:
  DB_USERNAME: ""
  DB_PASSWORD: ""
  JWT_AUTH_USERNAME: ""
  JWT_AUTH_PASSWORD: ""
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY_ID: ""
  AMAZON_BEDROCK_AGENT_ID: ""
  OPENSEARCH_USERNAME: ""
  OPENSEARCH_PASSWORD: ""
  GRAFANA_API_KEY: ""
  JAEGER_REPORTER_COLLECTOR_USER: ""
  JAEGER_REPORTER_COLLECTOR_PASSWORD: ""
