---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.3.0
    helm.sh/chart: postgresql-15.5.16
  annotations:
    meta.helm.sh/release-name: postgresql
    meta.helm.sh/release-namespace: monitoring
type: Opaque
data:
  postgres-user: ""
  POSTGRES_USERNAME: ""
  postgres-password: ""
  postgres-root-password: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_ROOT_PASSWORD: ""