apiVersion: v2
name: alertmanager-snmp-notifier
description: The SNMP Notifier handles alerts coming from Prometheus Alertmanager and relay them as SNMP traps.
home: https://github.com/maxwo/snmp_notifier
sources:
  - https://github.com/maxwo/snmp_notifier
type: application
version: 0.3.0
appVersion: v1.5.0
keywords:
  - monitoring
maintainers:
  - name: maxwo
    email: maxime.wojtczak.pub@icloud.com
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
