snmpNotifier:
  snmpDestinations:
    - 127.0.0.1:162

  snmpTemplates:
    description: |
      {{- if .Alerts -}}
      {{ len .Alerts }}/{{ len .DeclaredAlerts }} alerts are firing:

      {{ range $severity, $alerts := (groupAlertsByLabel .Alerts "severity") -}}
      Status: {{ $severity }}

      {{- range $index, $alert := $alerts }}
      - Alert: {{ $alert.Labels.alertname }}
        Summary: {{ $alert.Annotations.summary }}
        Description: {{ $alert.Annotations.description }}
      {{ end }}
      {{ end }}
      {{ else -}}
      Status: OK
      {{- end -}}

    extraFields:
      - subId: 4
        template: |
          {{- if .Alerts -}}
          Status: NOK
          {{- else -}}
          Status: OK
          {{- end -}}
      - subId: 5
        template: |
          This is a constant
