{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-fastly-exporter.secretName" . }}
  labels:
    {{- include "prometheus-fastly-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  fastly-api-token: {{ required "A Fastly token is required" .Values.fastly.token | b64enc }}
{{- end -}}
