---
apiVersion: v2
description: A Helm chart for the Prometheus NGINX Exporter
name: prometheus-nginx-exporter
version: 0.2.1
appVersion: 0.11.0
home: https://github.com/nginxinc/nginx-prometheus-exporter
sources:
  - https://github.com/nginxinc/nginx-prometheus-exporter
  - https://github.com/prometheus-community/helm-charts
keywords:
  - prometheus
  - nginx
  - monitoring
maintainers:
  - name: nlamirault
    email: nicolas.lamirault@gmail.com
  - name: zeritti
    email: rootsandtrees@posteo.de
icon: https://raw.githubusercontent.com/cncf/artwork/master/prometheus/icon/color/prometheus-icon-color.svg
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Nginx exporter
      url: https://github.com/nginxinc/nginx-prometheus-exporter
  artifacthub.io/maintainers: |
    - name: nlamirault
      email: nicolas.lamirault@gmail.com

dependencies:
  - name: nginx
    version: "15.3.4"
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
