{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-systemd-exporter.serviceAccountName" . }}
  namespace: {{ include "prometheus-systemd-exporter.namespace" . }}
  labels: 
    {{- include "prometheus-systemd-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
