# -- Helm chart name override
nameOverride: null

# -- Helm chart full name override
fullnameOverride: null

# -- Number of replicas to run
replicas: 1

image:
  # -- Docker image registry where the Docker image resides
  repository: grafana/snyk_exporter
  # -- Docker image pull policy
  pullPolicy: IfNotPresent
  # -- Docker image tag. If not specified, the chart `appVersion` is used by default.
  tag: null

# -- List of Docker image pull sercrets
imagePullSecrets: []

# -- Pod annotations
podAnnotations: {}

# -- Pod security context
# @default -- See the [`values.yaml`](values.yaml) file
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# -- Container security context
# @default -- See the [`values.yaml`](values.yaml) file
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

# -- Pod resources
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

# -- Node selector
nodeSelector: {}

# -- Pod tolerations
tolerations: []

# -- Pod affinity
affinity: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: null

service:
  # -- Service type
  type: ClusterIP
  # -- Service port. If not specified, the `exporter.port` is used by default.
  port: null

secret:
  # -- Whether the secret holding the Snyk API key will be created or not
  create: true
  # -- Whether the Snyk API token from the secret should be used as environment variable
  asEnv: true
  # -- Name of the secret. Automatically generated if not set.
  name: ""
  # -- Key under which the Snyk API key will be stored in the Secret
  key: snykApiToken
  # -- Labels for the secret
  labels: {}
  # - Annotations for the secret
  annotations: {}

exporter:
  # -- Snyk API URL (legacy). If not specified, `https://snyk.io/api/v1` is used by default.
  apiURL: null
  # -- Snyk REST API URL. If not specified, `https://api.snyk.io/rest` is used by default.
  restAPIURL: null
  # -- Snyk REST API Version. If not set, `2023-06-22` is used by default.
  restAPIVersion: null
  # -- Snyk API token. This must be provided if `secret.create: true`.
  apiToken: null
  # -- Polling interval for requesting data from Snyk API in seconds. If not specified, `600` is used by default.
  interval: null
  # -- List of Snyk organization IDs. If not specified, all organizations will be scraped.
  organizations: []
  # -- List of Snyk targets. If not specified, all targets will be scraped.
  targets: []
  # -- List of Snyk project origins. If not specified, all origins will be scraped.
  origins: []
  # -- Project filter (e.g. `attributes.imageCluster=mycluster`)
  projectFilter: null
  # -- Timeout for requests against Snyk API in seconds. If not specified, `10` is used by default.
  timeout: null
  # -- Metrics port number for the exporter
  port: 9532
  # -- Log level (`debug`, `info`, `warn`, `error` or `fatal`). If not set, `info` is used by default.
  logLevel: null
  # -- Log target and format
  logFormat: null
  # -- Path to the file containing commandline arguments insude the container
  argsFile: null
  # -- List of extra command line arguments to pass to the exporter
  extraArgs: []

serviceMonitor:
  # -- Whether the Prometheus `ServiceMonitor` will be created or not
  create: false
  # -- Labels applied to the `ServiceMonitor` resource
  labels: {}
  # -- Metrics scrape interval
  interval: null
  # -- Metrics scrape timeout
  scrapeTimeout: null
  # -- List of relabelings
  relabelings: []
  # -- List of metric relabelings
  metricRelabelings: []
