{{- if not .Values.configSecret.enabled -}}
{{- $fullName := include "prometheus-ipmi-exporter.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "prometheus-ipmi-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    modules:
{{- toYaml .Values.modules | nindent 6 }}
{{- end }}
