apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-ipmi-exporter.fullname" . }}
  labels:
    {{- include "prometheus-ipmi-exporter.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-ipmi-exporter.selectorLabels" . | nindent 4 }}
