---
replicaCount: 1

secret:
  enabled: false
  name: "secret-jumppod"
  mountPath: {}
  subPath: {}
  readOnly: true
  data: {}

configMap:
  enabled: false
  name: "config-jumppod"
  mountPath: /app/core/config
  readOnly: true
  data:
    .app.config.json: |-
        {
           "AppName": "Jumppos Helm Template",
           "GRPCTimeout": 10,
           "CacheExpiry": 300,
           "CacheCleanup": 600,
           "DefaultPageLimit": 3,
           "ClientTimeout": 10
        }

image:
  repository: devopscorner/cicd
  pullPolicy: IfNotPresent # IfNotPresent -or- Always
  tag: "alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
  namespace: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

livenessProbe: {}

readinessProbe: {}

## Persist data to a persistent volume
persistence:
  enabled: false
  # storageClass: "gp2"
  accessMode: ReadWriteOnce
  capacity: 20Gi
  size: 8Gi
  annotations: {}
  selector: {}

securityContext: {}

service:
  enable: false
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ""
      paths: []
  tls: []

application:
  enabled: true
  env:
    - name: HELM_TEMPLATE_NAME
      value: jumppod

envFrom:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  enabled: true
  select:
    node: "default"

tolerations: []

affinity: {}
