{{- if and .Values.secret.create .Values.exporter.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "this.secretName" . }}
  labels: {{- (mergeOverwrite (include "this.labels" . | fromYaml) .Values.secret.labels) | toYaml | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.secret.key }}: {{ .Values.exporter.apiToken | toString | b64enc }}
{{- end }}
