apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.fullname" . }}
  labels: {{- include "this.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default .Values.exporter.port .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: {{- include "this.selectorLabels" . | nindent 4 }}
