{{- if and ( .Values.cloudsqlproxy.enabled ) ( not .Values.cloudsqlproxy.credentialsSecret ) ( not .Values.cloudsqlproxy.workloadIdentity.enabled ) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "prometheus-mysql-exporter.cloudsqlsecret" . }}
  namespace: {{ include "prometheus-mysql-exporter.namespace" . }}
  labels:
    {{- include "prometheus-mysql-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.cloudsqlproxy.credentials | b64enc }}
{{- end }}
