{{- if not .Values.mysql.existingConfigSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-mysql-exporter.secretName" . }}
  namespace: {{ include "prometheus-mysql-exporter.namespace" . }}
  labels:
    {{- include "prometheus-mysql-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ template "prometheus-mysql-exporter.secretKey" . }}: |
      [client]
      host={{ .Values.mysql.host }}
      port={{ .Values.mysql.port }}
      user={{ .Values.mysql.user }}
      {{- if and (.Values.mysql.pass) (not .Values.mysql.existingPasswordSecret.name) }}
      password={{ .Values.mysql.pass }}
      {{- end }}
      {{- if .Values.mysql.db }}
      database={{ .Values.mysql.db }}
      {{- end }}
      {{- if .Values.mysql.protocol }}
      protocol={{ .Values.mysql.protocol }}
      {{- end }}
      {{- range $param := .Values.mysql.additionalConfig}}
      {{ $param }}
      {{- end }}
      {{- if .Values.serviceMonitor.multipleTarget.enabled -}}
      {{- template "render_mysql_targets" . -}}
      {{- end -}}
{{- end }}
