apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-mysql-exporter.fullname" . }}
  namespace: {{ include "prometheus-mysql-exporter.namespace" . }}
  labels:
    {{- include "prometheus-mysql-exporter.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "prometheus-mysql-exporter.selectorLabels" . | nindent 4 }}
