{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-mysql-exporter.serviceAccountName" . }}
  namespace: {{ include "prometheus-mysql-exporter.namespace" . }}
  labels:
    app: {{ template "prometheus-mysql-exporter.name" . }}
    chart: {{ template "prometheus-mysql-exporter.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- with .Values.serviceAccount.annotations  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.cloudsqlproxy.workloadIdentity.enabled }}
    {{ include "prometheus-mysql-exporter.workloadIdentityAnnotation" . }}
  {{- end }}
{{- end -}}
