apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager-snmp-notifier.fullname" . }}
  labels:
    {{- include "alertmanager-snmp-notifier.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  {{- end }}
spec:
{{- if .Values.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.ipDualStack.ipFamilyPolicy }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alertmanager-snmp-notifier.selectorLabels" . | nindent 4 }}
